# Generated by Django 4.2.3 on 2023-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_grocery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
