# Generated by Django 4.2.3 on 2023-07-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grocery_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='description',
            field=models.TextField(default='Add'),
        ),
    ]
